### ISSUE TITLE
[DEV] Beta-Testing

### ISSUE THREAD

**Issue by EnKdev** [EnKdev/EnKdevs-Item-Trackers#16]
**Description**
Before V3.0.0 of the OoT Tracker can go live, it has to be tested internally for a week.

**Expected version**
OoT Tracker - V3.0.0

**To-Dos**

- [x] [UI Redesign/UI Rearrangements](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/6)
- [x] [Rework deleting tracker saves](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/9)
- [x] [Restructure save structure](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/19)
- [x] [Autosaving/Autoloading tracker saves](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/8)
- [x] [Implement HC/HP Tracking](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/7)
