### ISSUE TITLE
[DEV] Beta-Testing

### ISSUE THREAD

**Issue by EnKdev** [EnKdev/EnKdevs-Item-Trackers#17]
**Description**
Before the MM Tracker can go live, it has to be tested internally for a week.

**Expected version**
MM Tracker - V1.0.0

**To-Dos**

- [ ] [Create UI Screens](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/10)
- [ ] [Gather Item Sprites](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/11)
- [ ] [Create Features for Sprite Swapping](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/13)
- [ ] [Autosaving/Autoloading tracker saves](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/14)
- [ ] [Deletion of tracker saves](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/15)
- [ ] [Load resources from archive](https://github.com/EnKdev/EnKdevs-Item-Trackers/issues/18)
